name: Build
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Gather info
        id: info
        run: |
          PACKAGE='ghcr.io/${{github.repository_owner}}/build-android'
          TAGS="${PACKAGE}:latest"
          echo "##[set-output name=package;]${PACKAGE,,}"
          echo "##[set-output name=tags;]${TAGS,,}"
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.1.2
        with:
          version: latest
      - name: Build image
        uses: docker/build-push-action@v2.4.0
        with:
          builder: ${{steps.buildx.outputs.name}}
          context: .
          tags: ${{steps.info.outputs.tags}}
          push: false
          load: true
      - name: Report image details
        run: >
          docker image history
          --format "table {{.Size}}\t{{.CreatedBy}}"
          ${{steps.info.outputs.package}}
      - name: Login into registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1.8.0
        with:
          registry: ghcr.io
          username: ${{secrets.CONTAINER_REGISTRY_USER}}
          password: ${{secrets.CONTAINER_REGISTRY_TOKEN}}
      - name: Push image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2.4.0
        with:
          builder: ${{steps.buildx.outputs.name}}
          context: .
          tags: ${{steps.info.outputs.tags}}
          push: true
