name: CI
on:
  pull_request:
    branches: main
  push:
    branches: main
permissions:
  contents: read
  packages: write
concurrency:
  group: ci-${{github.ref}}
  cancel-in-progress: ${{github.ref != 'refs/heads/main'}}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Gather info
        id: info
        run: |
          PACKAGE='ghcr.io/${{github.repository_owner}}/build-android'
          TAGS="${PACKAGE}:latest"
          echo "##[set-output name=package;]${PACKAGE,,}"
          echo "##[set-output name=tags;]${TAGS,,}"
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.6.0
        with:
          version: latest
      - name: Build image
        uses: docker/build-push-action@v2.8.0
        with:
          builder: ${{steps.buildx.outputs.name}}
          context: .
          tags: ${{steps.info.outputs.tags}}
          push: false
          load: true
      - name: Report image details
        run: >
          docker image history
          --format "table {{.Size}}\t{{.CreatedBy}}"
          ${{steps.info.outputs.package}}
      - name: Login into registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1.12.0
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{github.token}}
      - name: Push image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2.8.0
        with:
          builder: ${{steps.buildx.outputs.name}}
          context: .
          tags: ${{steps.info.outputs.tags}}
          push: true
